### ISSUE TITLE
Default Drupal 7 recipe fails - Using php 7.4 instead of 7.2 works

### ISSUE THREAD

**Issue by klonos** [lando/drupal#9] opened 2022-02-01 08:58 UTC
I've been using this for some time now without any issues:

```
lando init \
  --recipe drupal7 \
  --webroot . \
  --name d7test \
  --option database=mariadb \

lando start
lando drush -y si standard --db-url=mysql://drupal7:drupal7@database:3306/drupal7 --site-name="D7 test site" --account-pass=password
```

But I recently started having issues:

```
You are about to create a /app/sites/default/settings.php file and CREATE the 'drupal7' database.
Do you want to continue? (y/n): y
Failed to create database: ERROR 2002 (HY000): Can't connect to MySQL server on 'database' (115)
[error]
```

I then noticed a couple of these php-related warnings:
```
...
Oh... and here are some vitals:

 NAME      d7test
 LOCATION  /Users/greg/drupal/d7test   
 RECIPE    drupal7                                    
 DOCS      https://docs.lando.dev/config/drupal7.html 

php version 7.2 is a legacy version! We recommend upgrading.
Let's get this party started! Starting app d7test...
php version 7.2 is a legacy version! We recommend upgrading.
landoproxyhyperion5000gandalfedition_proxy_1 is up-to-date
...
```

So I updated the init command to include `--option php=7.4` and things started working as expected again. Not sure if this is because D7 requires an updated version of php now(?), or if it is lando-specific, but if you update the D7 recipe to use php 7.4 by default, then this issue is solved.

**Comment by gitressa** [comment] 2022-02-01 10:51
I can confirm this @klonos and have made a Merge Request which updates PHP version to 7.4 for the Drupal 7 recipe: #10.

However, if I try to test it locally, I still get PHP 7.2 ... From my understanding, I ought to get the updated version with these steps:

**Download the Drupal recipe, check out the relevant Merge Request and build it with yarn**
```
git clone https://github.com/lando/drupal
cd drupal
git fetch origin pull/10/head:d7_php74
git checkout d7_php74
yarn install
```

**Create the plugin folder, symlink to the drupal recipe above, clear cache and check it is registered**
```
mkdir ~/.lando/plugins
cd ~/.lando/plugins/
ln -s ~/drupal
lando config --clear
lando config --path plugins | grep drupal
```

I see now all Drupal recipes are doubled (except for `drupal10`) perhaps that's the reason why?
```
$ lando init
? From where should we get your app's codebase? current working directory
? What recipe do you want to use? 
  backdrop 
  drupal10 
  drupal6 
❯ drupal6 
  drupal7 
  drupal7 
  drupal8 
(Move up and down to reveal more choices)
```

**Comment by gitressa** [comment] 2022-02-01 23:09
The method above is probably only useful when adding a new recipe, but not so much for tweaking an existing.

To test it, I tried copying the `drupal7` recipe into a new recipe (`drupal74`), updated the name to `drupal74` in `~/drupal/recipes/drupal74/builder.js` and `~/drupal/recipes/drupal74/init.js`, and cleared cache.

Now I could successfully create a Lando instance with PHP `7.4` and install Drupal 7 without any PHP `7.2` warnings:

**Create it**
```
$ lando init \
>   --source remote \
>   --remote-url https://ftp.drupal.org/files/projects/drupal-7.87.tar.gz \
>   --remote-options="--strip-components 1" \
>   --recipe drupal74 \
>   --webroot . \
>   --name my-first-drupal7-app
[...]
Your app has been initialized!
```
**Install Drupal 7**
```
$ drush site:install --db-url=mysql://drupal74:drupal74@database/drupal74 -y
You are about to DROP all tables in your 'drupal74' database. Do you want to continue? (y/n): y
Starting Drupal installation. This takes a while. Consider using the --notify global option. [ok]
Installation complete.  User name: admin  User password: WhRfZLBPyP [ok]

$ drush uli -l https://my-first-drupal7-app.lndo.site
https://my-first-drupal7-app.lndo.site/user/reset/1/1643756150/_9ZSfQ6E8TWHWBJDwa8KD9yAQmwzL7GpHZXIA21RfHU/login
```

**Comment by labboy0276** [comment] 2022-03-02 16:14
This is resolved in 0.5.2 version of this plugin

**Closed by labboy0276** 2022-03-02 16:14 UTC
Labels: bug

**Comment by jonasflint** [comment] 2024-09-15 20:57
2024 and this still not working for me.

**Comment by AaronFeledy** [comment] 2024-09-15 21:32
@jonasflint In 2022 the drupal7 recipe was updated to default to PHP 7.4, resolving this issue. What is not working for you?
