### ISSUE TITLE
Problem with Drupal10 recepite default composer version

### ISSUE THREAD

**Issue by cdt-team** [lando/drupal#75] opened 2023-10-31 15:29 UTC
Hello for work correctly with Drupal 10 we should use at least Composer version 2.3.6 or higher, as suggest in the [documentation](https://www.drupal.org/project/drupal/releases/10.0.0#:~:text=for%20more%20information.-,Composer%20requirements,receive%20warnings%20on%20older%20versions.)

I try to install Drupal 10 as suggested in the lando recepit documentation, and if I install the **dev** repo composer version is set to 2.4.4, https://docs.lando.dev/drupal/getting-started.html:
`lando composer create-project drupal/recommended-project:10.0.x-dev@dev tmp && cp -r tmp/. . && rm -rf tmp`

but if i try to install the latest Drupal 10 version the composer version is 2.2.x, and I not find a correct way to override the composer version inside the .lando.yml
`lando composer create-project drupal/recommended-project:10.x tmp && cp -r tmp/. . && rm -rf tmp`

Here is my lando.yml file

```
name: d10-test
recipe: drupal10
excludes:
  - vendor
  - node_modules
  - modules/contrib
services:
  cache:
    type: redis
    persist: true
config:
  php: 8.2
  composer_version: 2-latest
  via: nginx
  webroot: web
tooling:
  redis-cli:
    service: cache
```

**Comment by pfrenssen** [comment] 2023-11-22 21:01
This is a bit puzzling. I had the same problem, and checking the logs at ~/.lando/logs I can see that the command `/bin/sh /helpers/install-composer.sh 2-latest` is always executed correctly. This should download the installer from https://getcomposer.org/installer and install it inside the `appserver` container at `/usr/local/bin/composer`.

I got it to work after messing about for a bit, but I could not retrace which change it was that solved it. Possibly there was another older `composer` binary present somewhere in the `$PATH`?

**Comment by reynoldsalec** [comment] 2024-04-01 23:44
Duplicate of https://github.com/lando/drupal/issues/31.

@pfrenssen note that install-composer.sh only runs when a `compoer_version` is passed in, so it could be that its not running `2-latest` unless the user has specified that? I don't think we set that in the Drupal recipe.

**Closed by reynoldsalec** 2024-04-01 23:44 UTC
Labels: Needs Triage
